
@startuml

title 基于GitHub的实验管理平台--类图

class users {
    <b>user_id</b> （用户ID）
    user_name （用户真实姓名）
    user_password （用户密码）
    user_disable （用户是否禁用）
    github_username （用户GitHub账号）

}

class teachers{

    <b>teacher_id</b> （老师工号）
    teacher_department （所属学院）
}

class students{

    <b>student_id</b> （学生学号）
    student_class （班级）
    student_department(学生所属学院)
    student_major(所属专业)
    student_sum （成绩汇总）

}
class systemAdmin{
    <b>systemAdmin_id</b> (管理员编号)
}

class courses{

    <b>course_id</b>（课程编号）
    course_name（课程名称）
    course_explain（课程简介）
    course_term（课程学期）
    course_major（课程专业）

}

class tests {

    <b>test_id</b> （实验编号）
    course_id（课程id）
    teacher_id(老师学工号)
    test_name （实验名称）
    test_explain （实验内容简介）
    test_last_time （实验截止日期）

}

class grades {

    <b>student_id</b> （学号）
    <b>test_id</b> （实验编号）
    grade_score （实验得分）
    grade_review （实验评语）
    grade_date （评改日期）

}


users <|- students
users <|- systemAdmin
users <|-- teachers
students "1" -- "n"  courses
teachers "n" -- "n"  courses
teachers "1" -- "n"  tests
courses  "1" -- "n"  tests
students "1" -- "n"  grades
tests "1" - "n"  grades

@enduml