@startuml
title 图书管系统的类图

Class 图书{
国际出版号
书名
作者
简介
可借数量
价格
出版社
出版日期
}

Class 预定记录{
预定日期
}
hide 预定记录 Circle


Class 借书记录{
借书日期
归还日期
}

Class 读者{
姓名
性别
身份证号
借书限额
已借图书数
}

Class 图书管理员{
职工号
姓名
}
Class 系统管理员{
职工号
姓名
}
Class 借书卡{
借书卡号
}
Class 逾期记录{
逾期天数
}
hide 逾期记录 Circle

Class 罚款细则
hide 罚款细则 Circle

图书 "1" - "*" 预定记录:被预定
预定记录 "*" - "1" 读者
读者 - 借书记录:查询
借书记录 "*" -- "1" 图书管理员:登记
借书记录 "*" -- "0..1" 逾期记录
罚款细则 "0..1" -- "*" 逾期记录:使用
系统管理员 "1.." -- "*" 图书:管理
读者 "1" -- "1" 借书卡:拥有
图书管理员 "1.." -- "*" 借书卡:管理
读者 "1.." -- "*" 图书:直接借阅
@enduml